export const UI_TEXT = {
  en: {
    common: {
      close: 'Close',
      remove: 'Remove',
      retry: 'Try again',
    },
    model: {
      onboardingTitle: 'Explore Saiyuen Bridge your way',
      onboardingBody:
        'Choose a starting point, then rotate the model, tap parts of the bridge, or switch modes whenever you like.',
      onboardingExploreTitle: 'Explore the bridge',
      onboardingExploreBody: 'Open bridge info, photos, and layer controls.',
      onboardingGuideTitle: 'Ask the guide',
      onboardingGuideBody: 'Get a guided tour or ask about structure, history, and symbolism.',
      onboardingDesignTitle: 'Imagine a redesign',
      onboardingDesignBody: 'Generate alternative bridge concepts and blend them into the live view.',
      onboardingDismiss: 'Skip for now',
      onboardingHint: 'Drag to rotate. Pinch to zoom. Tap a bridge part to learn more.',
      languageToggle: '中文',
      languageToggleShort: 'EN',
      infoFabOpen: 'Bridge Info',
      infoFabClose: 'Close info',
      designFabOpen: 'Design Bridge',
      designFabClose: 'Close designer',
      cameraLoading: 'Loading Saiyuen Bridge...',
      cameraUnavailableTitle: 'Camera unavailable',
      cameraUnavailableBody: 'You can still explore the 3D bridge, info panel, and guide without the live camera feed.',
      shareSuccess: 'Link copied to clipboard',
      shareError: 'Could not copy the link',
      infoTitle: 'Saiyuen Bridge Information',
      elementsTitle: 'Bridge Elements',
      videoTitle: 'Bridge Video',
      slideLabels: ['Front render', 'Alternate render', 'How to explore'],
      baseTitle: 'Foundation arch',
      baseBody: 'Stone base, arch, and supports',
      structureTitle: 'Deck and railings',
      structureBody: 'Upper walkway and protective edges',
      shareTooltip: 'Share Saiyuen',
    },
    chat: {
      fabOpen: 'Ask the bridge guide',
      fabClose: 'Close guide',
      title: 'Bridge Guide',
      restore: 'Restore view',
      nothingToRestore: 'Nothing to restore',
      clearConversation: 'Clear conversation',
      empty:
        'Ask about the Saiyuen Bridge, or tap a part of the 3D model to get a focused explanation.',
      startTour: 'Start guided tour',
      designBridge: 'Design bridge',
      tappedPrefix: 'Tapped:',
      screenshotSuccess: 'Screenshot saved',
      screenshotError: 'Could not capture a screenshot',
      screenshotTooltip: 'Save screenshot',
      speak: 'Speak',
      stopListening: 'Stop listening',
      listening: 'Listening...',
      askPlaceholder: 'Ask about the bridge...',
      agentError: 'Could not reach the guide. Check your API key and try again.',
      rotationHints: {
        front: 'Front view. You can see the full arch clearly from here.',
        side: 'Side profile. This angle is great for understanding the arch curvature.',
        rear: 'Rear view of the bridge.',
      },
      suggestedPrompts: [
        'Who built this bridge?',
        'Tell me about the foundation',
        'What does the bridge symbolize?',
        'Show me the structure only',
        'What is the span of the bridge?',
      ],
    },
    designer: {
      title: 'Bridge Designer',
      statusAnalysing: 'Analyzing photo...',
      statusRefreshing: 'Refreshing...',
      statusGenerating: 'Generating...',
      usingPhoto: 'Using your photo',
      usingArCapture: 'Captured from live view',
      usingPhotoBody: 'The image will be analyzed before generating design concepts.',
      uploadPhoto: 'Upload photo',
      uploadPhotoBody: 'Use an image from your device',
      captureArView: 'Capture live view',
      captureArViewBody: 'Use the current bridge placement',
      captureArUnavailable: 'Live camera capture is unavailable right now',
      styleLabel: 'STYLE - choose one or more',
      lightingLabel: 'LIGHT',
      generateForPhoto: (count) => `Design for my photo - ${count}`,
      generate: (count) => `Generate - ${count} style${count > 1 ? 's' : ''}`,
      historyLabel: 'HISTORY',
      blendLabel: 'Blend with reality',
      miniBarViewDesigns: 'View designs',
      miniBarClearOverlay: 'Clear overlay',
      regenerateStyle: 'Regenerate this style',
      generationFailed: 'Could not generate designs. Please try again.',
      regenerationFailed: 'Could not refresh that design.',
      captureFailed: 'Could not capture the live view.',
      fileReadFailed: 'Could not read that photo.',
      styleLabels: {
        'stone-arch': 'Stone Arch',
        'concrete':   'Sleek Concrete',
        'steel-glass':'Steel & Glass',
        'timber':     'Timber Beam',
        'ancient':    'Ancient Heritage',
        'biophilic':  'Biophilic',
        'bamboo':     'Bamboo',
      },
      lightingLabels: {
        'dawn':   'Dawn',
        'midday': 'Midday',
        'golden': 'Golden Hour',
        'night':  'Night',
      },
    },
  },
  zh: {
    common: {
      close: '關閉',
      remove: '移除',
      retry: '再試一次',
    },
    model: {
      onboardingTitle: '用你的方式探索西園橋',
      onboardingBody: '先選一個起點，之後你可以旋轉模型、點擊橋體部件，或隨時切換模式。',
      onboardingExploreTitle: '探索橋樑',
      onboardingExploreBody: '查看橋樑資訊、照片與圖層控制。',
      onboardingGuideTitle: '詢問導覽員',
      onboardingGuideBody: '開始導覽，或詢問結構、歷史與文化意義。',
      onboardingDesignTitle: '想像改造方案',
      onboardingDesignBody: '產生不同橋樑設計，並疊加到即時畫面上。',
      onboardingDismiss: '稍後再看',
      onboardingHint: '拖曳可旋轉，雙指可縮放，點擊橋體部件可了解更多。',
      languageToggle: 'EN',
      languageToggleShort: '中文',
      infoFabOpen: '橋樑資訊',
      infoFabClose: '關閉資訊',
      designFabOpen: '設計橋樑',
      designFabClose: '關閉設計器',
      cameraLoading: '正在載入西園橋...',
      cameraUnavailableTitle: '無法使用相機',
      cameraUnavailableBody: '你仍可探索 3D 橋樑、資訊面板與導覽功能。',
      shareSuccess: '連結已複製到剪貼簿',
      shareError: '無法複製連結',
      infoTitle: '西園橋資訊',
      elementsTitle: '橋樑部件',
      videoTitle: '橋樑影片',
      slideLabels: ['正面視圖', '替代視圖', '操作說明'],
      baseTitle: '基礎拱橋',
      baseBody: '石造基座、拱圈與支撐結構',
      structureTitle: '橋面與欄杆',
      structureBody: '上層步道與保護邊緣',
      shareTooltip: '分享西園橋',
    },
    chat: {
      fabOpen: '詢問橋樑導覽員',
      fabClose: '關閉導覽',
      title: '橋樑導覽',
      restore: '還原視圖',
      nothingToRestore: '目前沒有需要還原的內容',
      clearConversation: '清除對話',
      empty: '詢問任何與西園橋有關的問題，或點擊 3D 模型上的部件取得重點解說。',
      startTour: '開始導覽',
      designBridge: '設計橋樑',
      tappedPrefix: '已點擊：',
      screenshotSuccess: '截圖已儲存',
      screenshotError: '無法擷取截圖',
      screenshotTooltip: '儲存截圖',
      speak: '語音輸入',
      stopListening: '停止聆聽',
      listening: '正在聆聽...',
      askPlaceholder: '詢問這座橋的相關問題...',
      agentError: '無法連接導覽功能，請檢查 API 金鑰後再試一次。',
      rotationHints: {
        front: '正面視角，可以清楚看到整個拱形。',
        side: '側面視角，最適合觀察拱橋曲線。',
        rear: '這是橋樑的背面視角。',
      },
      suggestedPrompts: [
        '這座橋是誰建造的？',
        '介紹一下橋的基礎結構',
        '這座橋象徵什麼？',
        '只顯示上部結構',
        '這座橋的跨度有多大？',
      ],
    },
    designer: {
      title: '橋樑設計器',
      statusAnalysing: '正在分析照片...',
      statusRefreshing: '正在刷新...',
      statusGenerating: '正在產生...',
      usingPhoto: '使用你的照片',
      usingArCapture: '來自即時畫面擷取',
      usingPhotoBody: '系統會先分析影像，再產生設計方案。',
      uploadPhoto: '上傳照片',
      uploadPhotoBody: '使用裝置中的圖片',
      captureArView: '擷取即時畫面',
      captureArViewBody: '使用目前橋樑位置',
      captureArUnavailable: '目前無法使用即時相機擷取',
      styleLabel: '風格 - 可多選',
      lightingLabel: '光線',
      generateForPhoto: (count) => `為我的照片設計 - ${count}`,
      generate: (count) => `產生設計 - ${count} 種`,
      historyLabel: '歷史紀錄',
      blendLabel: '與真實畫面融合',
      miniBarViewDesigns: '查看設計',
      miniBarClearOverlay: '清除疊圖',
      regenerateStyle: '重新產生此風格',
      generationFailed: '無法產生設計，請再試一次。',
      regenerationFailed: '無法刷新此設計。',
      captureFailed: '無法擷取即時畫面。',
      fileReadFailed: '無法讀取這張照片。',
      styleLabels: {
        'stone-arch': '石拱橋',
        'concrete':   '清水混凝土',
        'steel-glass':'鋼索玻璃橋',
        'timber':     '木樑橋',
        'ancient':    '古典遺址',
        'biophilic':  '仿生橋',
        'bamboo':     '竹橋',
      },
      lightingLabels: {
        'dawn':   '黎明',
        'midday': '正午',
        'golden': '黃金時段',
        'night':  '夜晚',
      },
    },
  },
};

export function getUIText(language) {
  return UI_TEXT[language] ?? UI_TEXT.en;
}
